apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-proto
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  type: ClusterIP
  ports:
  - port: 4020
    targetPort: 4020
    protocol: TCP
    name: grcp
  selector:
    app: {{ .Chart.Name }}
